/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_demo_HelloCPP */

#ifndef _Included_ndk_demo_HelloCPP
#define _Included_ndk_demo_HelloCPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_demo_HelloCPP
 * Method:    sayHelloCPP
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ndk_demo_HelloCPP_sayHelloCPP
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
