/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_TestJNIInstanceVariable */

#ifndef _Included_com_example_ndk_TestJNIInstanceVariable
#define _Included_com_example_ndk_TestJNIInstanceVariable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_TestJNIInstanceVariable
 * Method:    modifyInstanceVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ndk_demo_TestJNIInstanceVariable_modifyInstanceVariable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
