/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_demo_TestJNICallBackMethod */

#ifndef _Included_ndk_demo_TestJNICallBackMethod
#define _Included_ndk_demo_TestJNICallBackMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_demo_TestJNICallBackMethod
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ndk_demo_TestJNICallBackMethod_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
