/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_demo_HelloJNICPP */

#ifndef _Included_ndk_demo_HelloMixture
#define _Included_ndk_demo_HelloMixture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_demo_HelloMixture
 * Method:    sayHelloMixture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ndk_demo_HelloMixture_sayHelloMixture
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
