/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_demo_Baby */

#ifndef _Included_ndk_demo_Baby
#define _Included_ndk_demo_Baby
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_demo_Baby
 * Method:    superMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ndk_demo_Baby_superMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
