/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_demo_TestJNIConstructor */

#ifndef _Included_ndk_demo_TestJNIConstructor
#define _Included_ndk_demo_TestJNIConstructor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_demo_TestJNIConstructor
 * Method:    getIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_ndk_demo_TestJNIConstructor_getIntegerObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
