/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_TestJNIStaticVariable */

#ifndef _Included_com_example_ndk_TestJNIStaticVariable
#define _Included_com_example_ndk_TestJNIStaticVariable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_TestJNIStaticVariable
 * Method:    modifyStaticVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ndk_demo_TestJNIStaticVariable_modifyStaticVariable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
