/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_demo_TestJNIReference */

#ifndef _Included_ndk_demo_TestJNIReference
#define _Included_ndk_demo_TestJNIReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_demo_TestJNIReference
 * Method:    getIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_ndk_demo_TestJNIReference_getIntegerObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     ndk_demo_TestJNIReference
 * Method:    anotherGetIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_ndk_demo_TestJNIReference_anotherGetIntegerObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
