/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_TestJNIPrimitiveArray */

#ifndef _Included_com_example_ndk_TestJNIPrimitiveArray
#define _Included_com_example_ndk_TestJNIPrimitiveArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_TestJNIPrimitiveArray
 * Method:    sumAndAverage
 * Signature: ([I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ndk_demo_TestJNIPrimitiveArray_sumAndAverage
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
