/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_demo_HelloJNI */

#ifndef _Included_ndk_demo_HelloJNI
#define _Included_ndk_demo_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_demo_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ndk_demo_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
