/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_TestJNIPrimitive */

#ifndef _Included_com_example_ndk_TestJNIPrimitive
#define _Included_com_example_ndk_TestJNIPrimitive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_TestJNIPrimitive
 * Method:    average
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_ndk_demo_TestJNIPrimitive_average
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
