/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_TestJNIString */

#ifndef _Included_com_example_ndk_TestJNIString
#define _Included_com_example_ndk_TestJNIString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_TestJNIString
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_demo_TestJNIString_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
